#!/usr/bin/env python3
import sys, os

sysplatform = sys.platform
if sysplatform == "win32":
    print( "Hooks not implemented yet" )
elif sysplatform == "darwin":
    print( "Hooks not implemented yet" )
elif sysplatform == "linux":
    print( "Hooks not implemented yet" )
